title: Danish A. Alvi
description: "A personal website for Danish A. Alvi"
permalink: ':title/'
baseurl: ""
url: "https://danalvi.github.io"

# Contact links
phone:
website: danalvi.github.io
linkedin: daalvi
github:  danalvi
twitter: _combinatorist
facebook:
instagram:
pinterest:

# Newsletter
mailchimp:

# Disqus
discus_identifier:


# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-feed

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
